//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var4_Policlinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Doctor { get; set; }
        public Nullable<int> Patient { get; set; }
        public string Information { get; set; }
    
        public virtual Doctor Doctor1 { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
